version: '3.3'

services:
  blog-upload:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: blog-upload:latest
    environment:
      NODE_ENV: ${NODE_ENV}
      API_PORT: ${API_PORT}
      DB_DEFAULT_HOST: ${DB_DEFAULT_HOST}
      DB_DEFAULT_TYPE: ${DB_DEFAULT_TYPE}
      DB_DEFAULT_PORT: ${DB_DEFAULT_PORT}
      DB_DEFAULT_USERNAME: ${DB_DEFAULT_USERNAME}
      DB_DEFAULT_PASSWORD: ${DB_DEFAULT_PASSWORD}
      DB_DEFAULT_DB_NAME: ${DB_DEFAULT_DB_NAME}
      JWT_APP_SECRET: ${JWT_APP_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      JWT_ISSUER: ${JWT_ISSUER}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET_CONTENT: ${AWS_S3_BUCKET_CONTENT}
      AWS_S3_BUCKET_THUMBNAIL: ${AWS_S3_BUCKET_THUMBNAIL}
      AWS_S3_BUCKET_AVATAR: ${AWS_S3_BUCKET_AVATAR}
      URL_BASE_DATA_REPLICATION: ${URL_BASE_DATA_REPLICATION}
      URL_BASE_NOTIFICATIONS: ${URL_BASE_NOTIFICATIONS}
    ports:
      - "${API_PORT}:${API_PORT}"
    container_name: blog-upload
    networks:
      - blog-net


networks:
  blog-net:
    external: true
